In [3]:
import pandas as pd
print(pd.__file__)
print(pd.__version__)

C:\Users\Sobiya Anjum\anaconda3\Lib\site-packages\pandas\__init__.py
2.3.3

In [4]:
df=pd.read_csv("amazon_ecommerce_1M.csv",nrows=10000)

In [5]:
df.head(10)

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed
5,U705397,P35203,Home,Decor,HP,6155.63,17.64,5069.65,3.3,22,360,S2139,5.0,2025-07-13,5,Bangalore,Mobile App,Credit Card,True,Returned
6,U498591,P46434,Home,Furniture,Adidas,1104.92,37.81,687.20,3.4,14,232,S6977,3.3,2026-02-10,1,Delhi,Mobile App,Debit Card,False,In Transit
7,U738720,P93227,Clothing,Kids,Sony,1899.42,63.23,698.36,3.3,18,87,S9751,4.3,2024-05-27,5,Delhi,Tablet,Credit Card,False,Delivered
8,U330283,P99733,Beauty,Makeup,Sony,3611.18,24.77,2716.69,3.9,17,166,S1916,3.8,2024-11-03,1,Chennai,Mobile App,UPI,False,In Transit
9,U694731,P51245,Beauty,Makeup,Apple,3826.65,8.46,3502.76,3.4,12,108,S9179,3.2,2024-12-27,1,Mumbai,Web,Cash on Delivery,False,Delivered

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             10000 non-null  object
 1   product_id          10000 non-null  object
 2   category            10000 non-null  object
 3   subcategory         10000 non-null  object
 4   brand               10000 non-null  object
 5   price               10000 non-null  float64
 6   discount            10000 non-null  float64
 7   final_price         10000 non-null  float64
 8   rating              10000 non-null  float64
 9   review_count        10000 non-null  int64
 10  stock               10000 non-null  int64
 11  seller_id           10000 non-null  object
 12  seller_rating       10000 non-null  float64
 13  purchase_date       10000 non-null  object
 14  shipping_time_days  10000 non-null  int64
 15  location            10000 non-null  object
 16  device              10000 non-null  object
 17  payment_method      10000 non-null  object
 18  is_returned         10000 non-null  bool
 19  delivery_status     10000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 1.5+ MB

In [17]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,13207.301858,29.095905,9941.594609,3.924850,31.896200,249.759900,3.759730,3.203500
std,18136.311929,14.697815,14374.517144,0.522677,41.872723,143.953134,0.722135,1.676117
min,200.140000,5.010000,111.800000,2.000000,0.000000,0.000000,2.500000,1.000000
25%,2732.495000,17.057500,1708.965000,3.600000,10.000000,126.000000,3.100000,2.000000
50%,4938.020000,28.235000,3759.295000,3.900000,19.000000,249.000000,3.800000,3.000000
75%,14062.495000,39.302500,10392.950000,4.300000,38.000000,374.000000,4.400000,5.000000
max,79885.530000,69.960000,74701.480000,5.000000,783.000000,500.000000,5.000000,6.000000

In [19]:
df.shape

(10000, 20)

In [20]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'location', 'device', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='object')

In [26]:
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)